/*
 * --------------------------------------------------------------------------------
 * <copyright company="Aspose" file="HtmlSaveOptionsData.swift">
 *   Copyright (c) 2019 Aspose.Words for Cloud
 * </copyright>
 * <summary>
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 * 
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 * 
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 * </summary>
 * --------------------------------------------------------------------------------
 */

import Foundation

public class HtmlSaveOptionsData : SaveOptionsData {
    // Gets or sets specifies version of HTML standard that should be used when saving the document to HTML or MHTML. Default value is Aspose.Words.Saving.HtmlVersion.Xhtml.
    public enum HtmlVersion : String, Codable
    { 
        // Enum value "xhtml"
        case xhtml = "Xhtml"
        
        // Enum value "html5"
        case html5 = "Html5"
        
    }

    // Gets or sets specifies in what format metafiles are saved when exporting to HTML, MHTML, or EPUB. Default value is Aspose.Words.Saving.HtmlMetafileFormat.Png, meaning that metafiles are rendered to raster PNG images.  Metafiles are not natively displayed by HTML browsers. By default, Aspose.Words converts WMF and EMF images into PNG files when exporting to HTML.Other options are to convert metafiles to SVG images or to export them as is without conversion. Some image transforms, in particular image cropping, will not be applied to metafile images if they are exported to HTML without conversion.
    public enum MetafileFormat : String, Codable
    { 
        // Enum value "png"
        case png = "Png"
        
        // Enum value "svg"
        case svg = "Svg"
        
        // Enum value "emfOrWmf"
        case emfOrWmf = "EmfOrWmf"
        
    }

    // Gets or sets controls how OfficeMath objects are exported to HTML, MHTML or EPUB.  Default value is HtmlOfficeMathOutputMode.Image.
    public enum OfficeMathOutputMode : String, Codable
    { 
        // Enum value "image"
        case image = "Image"
        
        // Enum value "mathML"
        case mathML = "MathML"
        
        // Enum value "text"
        case text = "Text"
        
    }

        
    // Gets or sets specifies whether negative left and right indents of paragraphs are allowed (not normalized).
    private var allowNegativeIndent : Bool?;
    // Gets or sets specifies a prefix which is added to all CSS class names. Default value is an empty string and generated CSS class names have no common prefix.  If this value is not empty, all CSS classes generated by Aspose.Words will start with the specified prefix.This might be useful, for example, if you add custom CSS to generated documents and want to prevent class name conflicts. If the value is not null or empty, it must be a valid CSS identifier.
    private var cssClassNamePrefix : String?;
    // Gets or sets specifies the name of the CSS file written when the document is exported to HTML.
    private var cssStyleSheetFileName : String?;
    // Gets or sets specifies how CSS styles are exported.
    private var cssStyleSheetType : String?;
    // Gets or sets specifies how the document should be split when saving.
    private var documentSplitCriteria : String?;
    // Gets or sets specifies the maximum level of headings at which to split the document.
    private var documentSplitHeadingLevel : Int?;
    // Gets or sets specifies the encoding to use when exporting.
    private var encoding : String?;
    // Gets or sets specifies whether to export built-in and custom document properties.
    private var exportDocumentProperties : Bool?;
    // Gets or sets controls how drop-down form fields are saved to HTML. Default value is false.
    private var exportDropDownFormFieldAsText : Bool?;
    // Gets or sets specifies whether font resources should be exported.
    private var exportFontResources : Bool?;
    // Gets or sets specifies whether fonts resources should be embedded to HTML in Base64 encoding.  Default is false.
    private var exportFontsAsBase64 : Bool?;
    // Gets or sets specifies how headers and footers are output.
    private var exportHeadersFootersMode : String?;
    // Gets or sets specifies whether images are saved in Base64 format.
    private var exportImagesAsBase64 : Bool?;
    // Gets or sets specifies whether language information is exported.
    private var exportLanguageInformation : Bool?;
    // Gets or sets controls how list labels are output.
    private var exportListLabels : String?;
    // Gets or sets specifies whether original URL should be used as the URL of the linked images. Default value is false.
    private var exportOriginalUrlForLinkedImages : Bool?;
    // Gets or sets specifies whether page margins is exported to HTML, MHTML or EPUB. Default is false.
    private var exportPageMargins : Bool?;
    // Gets or sets specifies whether page setup is exported.
    private var exportPageSetup : Bool?;
    // Gets or sets specifies whether font sizes should be output in relative units when saving.
    private var exportRelativeFontSize : Bool?;
    // Gets or sets specifies whether to write the roundtrip information when saving to HTML Default value is true.
    private var exportRoundtripInformation : Bool?;
    // Gets or sets controls how textboxes represented by Aspose.Words.Drawing.Shape are saved to HTML, MHTML or EPUB. Default value is false.    When set to true, exports textboxes as inline \&quot;svg\&quot; elements. When false, exports as \&quot;image\&quot; elements.
    private var exportTextBoxAsSvg : Bool?;
    // Gets or sets controls how text input form fields are saved.
    private var exportTextInputFormFieldAsText : Bool?;
    // Gets or sets specifies whether to write page numbers to table of contents when saving.
    private var exportTocPageNumbers : Bool?;
    // Gets or sets specifies whether to write the DOCTYPE declaration when saving.
    private var exportXhtmlTransitional : Bool?;
    // Gets or sets controls which font resources need subsetting when saving.
    private var fontResourcesSubsettingSizeThreshold : Int?;
    // Gets or sets specifies the physical folder where fonts are saved when exporting a document.
    private var fontsFolder : String?;
    // Gets or sets specifies the name of the folder used to construct font URIs.
    private var fontsFolderAlias : String?;
    // Gets or sets specifies version of HTML standard that should be used when saving the document to HTML or MHTML. Default value is Aspose.Words.Saving.HtmlVersion.Xhtml.
    private var htmlVersion : HtmlVersion?;
    // Gets or sets specifies the output resolution for images when exporting.
    private var imageResolution : Int?;
    // Gets or sets specifies the physical folder where images are saved when exporting a document.
    private var imagesFolder : String?;
    // Gets or sets specifies the name of the folder used to construct image URIs.
    private var imagesFolderAlias : String?;
    // Gets or sets specifies in what format metafiles are saved when exporting to HTML, MHTML, or EPUB. Default value is Aspose.Words.Saving.HtmlMetafileFormat.Png, meaning that metafiles are rendered to raster PNG images.  Metafiles are not natively displayed by HTML browsers. By default, Aspose.Words converts WMF and EMF images into PNG files when exporting to HTML.Other options are to convert metafiles to SVG images or to export them as is without conversion. Some image transforms, in particular image cropping, will not be applied to metafile images if they are exported to HTML without conversion.
    private var metafileFormat : MetafileFormat?;
    // Gets or sets controls how OfficeMath objects are exported to HTML, MHTML or EPUB.  Default value is HtmlOfficeMathOutputMode.Image.
    private var officeMathOutputMode : OfficeMathOutputMode?;
    // Gets or sets specifies whether or not use pretty formats output.
    private var prettyFormat : Bool?;
    // Gets or sets specifies whether font family names used in the document are resolved and substituted according to FontSettings when being written into HTML-based formats. default value is false.
    private var resolveFontNames : Bool?;
    // Gets or sets specifies a physical folder where all resources like images, fonts, and external CSS are saved when a document is exported to HTML. Default is an empty string.
    private var resourceFolder : String?;
    // Gets or sets specifies the name of the folder used to construct URIs of all resources written into an HTML document.  Default is an empty string.
    private var resourceFolderAlias : String?;
    // Gets or sets specifies whether images are scaled by Aspose.Words to the bounding shape size when exporting.
    private var scaleImageToShapeSize : Bool?;
    // Gets or sets controls how table, row and cell widths are exported.
    private var tableWidthOutputMode : String?;
        
    private enum CodingKeys: String, CodingKey {
        case allowNegativeIndent;
        case cssClassNamePrefix;
        case cssStyleSheetFileName;
        case cssStyleSheetType;
        case documentSplitCriteria;
        case documentSplitHeadingLevel;
        case encoding;
        case exportDocumentProperties;
        case exportDropDownFormFieldAsText;
        case exportFontResources;
        case exportFontsAsBase64;
        case exportHeadersFootersMode;
        case exportImagesAsBase64;
        case exportLanguageInformation;
        case exportListLabels;
        case exportOriginalUrlForLinkedImages;
        case exportPageMargins;
        case exportPageSetup;
        case exportRelativeFontSize;
        case exportRoundtripInformation;
        case exportTextBoxAsSvg;
        case exportTextInputFormFieldAsText;
        case exportTocPageNumbers;
        case exportXhtmlTransitional;
        case fontResourcesSubsettingSizeThreshold;
        case fontsFolder;
        case fontsFolderAlias;
        case htmlVersion;
        case imageResolution;
        case imagesFolder;
        case imagesFolderAlias;
        case metafileFormat;
        case officeMathOutputMode;
        case prettyFormat;
        case resolveFontNames;
        case resourceFolder;
        case resourceFolderAlias;
        case scaleImageToShapeSize;
        case tableWidthOutputMode;
        case invalidCodingKey;
    }
        
    public override init() {
        super.init();
    }
    
    public required init(from decoder: Decoder) throws {
        try super.init(from: decoder);
        let container = try decoder.container(keyedBy: CodingKeys.self);
        self.allowNegativeIndent = try container.decodeIfPresent(Bool.self, forKey: .allowNegativeIndent);
        self.cssClassNamePrefix = try container.decodeIfPresent(String.self, forKey: .cssClassNamePrefix);
        self.cssStyleSheetFileName = try container.decodeIfPresent(String.self, forKey: .cssStyleSheetFileName);
        self.cssStyleSheetType = try container.decodeIfPresent(String.self, forKey: .cssStyleSheetType);
        self.documentSplitCriteria = try container.decodeIfPresent(String.self, forKey: .documentSplitCriteria);
        self.documentSplitHeadingLevel = try container.decodeIfPresent(Int.self, forKey: .documentSplitHeadingLevel);
        self.encoding = try container.decodeIfPresent(String.self, forKey: .encoding);
        self.exportDocumentProperties = try container.decodeIfPresent(Bool.self, forKey: .exportDocumentProperties);
        self.exportDropDownFormFieldAsText = try container.decodeIfPresent(Bool.self, forKey: .exportDropDownFormFieldAsText);
        self.exportFontResources = try container.decodeIfPresent(Bool.self, forKey: .exportFontResources);
        self.exportFontsAsBase64 = try container.decodeIfPresent(Bool.self, forKey: .exportFontsAsBase64);
        self.exportHeadersFootersMode = try container.decodeIfPresent(String.self, forKey: .exportHeadersFootersMode);
        self.exportImagesAsBase64 = try container.decodeIfPresent(Bool.self, forKey: .exportImagesAsBase64);
        self.exportLanguageInformation = try container.decodeIfPresent(Bool.self, forKey: .exportLanguageInformation);
        self.exportListLabels = try container.decodeIfPresent(String.self, forKey: .exportListLabels);
        self.exportOriginalUrlForLinkedImages = try container.decodeIfPresent(Bool.self, forKey: .exportOriginalUrlForLinkedImages);
        self.exportPageMargins = try container.decodeIfPresent(Bool.self, forKey: .exportPageMargins);
        self.exportPageSetup = try container.decodeIfPresent(Bool.self, forKey: .exportPageSetup);
        self.exportRelativeFontSize = try container.decodeIfPresent(Bool.self, forKey: .exportRelativeFontSize);
        self.exportRoundtripInformation = try container.decodeIfPresent(Bool.self, forKey: .exportRoundtripInformation);
        self.exportTextBoxAsSvg = try container.decodeIfPresent(Bool.self, forKey: .exportTextBoxAsSvg);
        self.exportTextInputFormFieldAsText = try container.decodeIfPresent(Bool.self, forKey: .exportTextInputFormFieldAsText);
        self.exportTocPageNumbers = try container.decodeIfPresent(Bool.self, forKey: .exportTocPageNumbers);
        self.exportXhtmlTransitional = try container.decodeIfPresent(Bool.self, forKey: .exportXhtmlTransitional);
        self.fontResourcesSubsettingSizeThreshold = try container.decodeIfPresent(Int.self, forKey: .fontResourcesSubsettingSizeThreshold);
        self.fontsFolder = try container.decodeIfPresent(String.self, forKey: .fontsFolder);
        self.fontsFolderAlias = try container.decodeIfPresent(String.self, forKey: .fontsFolderAlias);
        self.htmlVersion = try container.decodeIfPresent(HtmlVersion.self, forKey: .htmlVersion);
        self.imageResolution = try container.decodeIfPresent(Int.self, forKey: .imageResolution);
        self.imagesFolder = try container.decodeIfPresent(String.self, forKey: .imagesFolder);
        self.imagesFolderAlias = try container.decodeIfPresent(String.self, forKey: .imagesFolderAlias);
        self.metafileFormat = try container.decodeIfPresent(MetafileFormat.self, forKey: .metafileFormat);
        self.officeMathOutputMode = try container.decodeIfPresent(OfficeMathOutputMode.self, forKey: .officeMathOutputMode);
        self.prettyFormat = try container.decodeIfPresent(Bool.self, forKey: .prettyFormat);
        self.resolveFontNames = try container.decodeIfPresent(Bool.self, forKey: .resolveFontNames);
        self.resourceFolder = try container.decodeIfPresent(String.self, forKey: .resourceFolder);
        self.resourceFolderAlias = try container.decodeIfPresent(String.self, forKey: .resourceFolderAlias);
        self.scaleImageToShapeSize = try container.decodeIfPresent(Bool.self, forKey: .scaleImageToShapeSize);
        self.tableWidthOutputMode = try container.decodeIfPresent(String.self, forKey: .tableWidthOutputMode);
    }

    public override func encode(to encoder: Encoder) throws {
        try super.encode(to: encoder);
        var container = encoder.container(keyedBy: CodingKeys.self);
        if (self.allowNegativeIndent != nil) {
            try container.encode(self.allowNegativeIndent, forKey: .allowNegativeIndent);
        }
        if (self.cssClassNamePrefix != nil) {
            try container.encode(self.cssClassNamePrefix, forKey: .cssClassNamePrefix);
        }
        if (self.cssStyleSheetFileName != nil) {
            try container.encode(self.cssStyleSheetFileName, forKey: .cssStyleSheetFileName);
        }
        if (self.cssStyleSheetType != nil) {
            try container.encode(self.cssStyleSheetType, forKey: .cssStyleSheetType);
        }
        if (self.documentSplitCriteria != nil) {
            try container.encode(self.documentSplitCriteria, forKey: .documentSplitCriteria);
        }
        if (self.documentSplitHeadingLevel != nil) {
            try container.encode(self.documentSplitHeadingLevel, forKey: .documentSplitHeadingLevel);
        }
        if (self.encoding != nil) {
            try container.encode(self.encoding, forKey: .encoding);
        }
        if (self.exportDocumentProperties != nil) {
            try container.encode(self.exportDocumentProperties, forKey: .exportDocumentProperties);
        }
        if (self.exportDropDownFormFieldAsText != nil) {
            try container.encode(self.exportDropDownFormFieldAsText, forKey: .exportDropDownFormFieldAsText);
        }
        if (self.exportFontResources != nil) {
            try container.encode(self.exportFontResources, forKey: .exportFontResources);
        }
        if (self.exportFontsAsBase64 != nil) {
            try container.encode(self.exportFontsAsBase64, forKey: .exportFontsAsBase64);
        }
        if (self.exportHeadersFootersMode != nil) {
            try container.encode(self.exportHeadersFootersMode, forKey: .exportHeadersFootersMode);
        }
        if (self.exportImagesAsBase64 != nil) {
            try container.encode(self.exportImagesAsBase64, forKey: .exportImagesAsBase64);
        }
        if (self.exportLanguageInformation != nil) {
            try container.encode(self.exportLanguageInformation, forKey: .exportLanguageInformation);
        }
        if (self.exportListLabels != nil) {
            try container.encode(self.exportListLabels, forKey: .exportListLabels);
        }
        if (self.exportOriginalUrlForLinkedImages != nil) {
            try container.encode(self.exportOriginalUrlForLinkedImages, forKey: .exportOriginalUrlForLinkedImages);
        }
        if (self.exportPageMargins != nil) {
            try container.encode(self.exportPageMargins, forKey: .exportPageMargins);
        }
        if (self.exportPageSetup != nil) {
            try container.encode(self.exportPageSetup, forKey: .exportPageSetup);
        }
        if (self.exportRelativeFontSize != nil) {
            try container.encode(self.exportRelativeFontSize, forKey: .exportRelativeFontSize);
        }
        if (self.exportRoundtripInformation != nil) {
            try container.encode(self.exportRoundtripInformation, forKey: .exportRoundtripInformation);
        }
        if (self.exportTextBoxAsSvg != nil) {
            try container.encode(self.exportTextBoxAsSvg, forKey: .exportTextBoxAsSvg);
        }
        if (self.exportTextInputFormFieldAsText != nil) {
            try container.encode(self.exportTextInputFormFieldAsText, forKey: .exportTextInputFormFieldAsText);
        }
        if (self.exportTocPageNumbers != nil) {
            try container.encode(self.exportTocPageNumbers, forKey: .exportTocPageNumbers);
        }
        if (self.exportXhtmlTransitional != nil) {
            try container.encode(self.exportXhtmlTransitional, forKey: .exportXhtmlTransitional);
        }
        if (self.fontResourcesSubsettingSizeThreshold != nil) {
            try container.encode(self.fontResourcesSubsettingSizeThreshold, forKey: .fontResourcesSubsettingSizeThreshold);
        }
        if (self.fontsFolder != nil) {
            try container.encode(self.fontsFolder, forKey: .fontsFolder);
        }
        if (self.fontsFolderAlias != nil) {
            try container.encode(self.fontsFolderAlias, forKey: .fontsFolderAlias);
        }
        if (self.htmlVersion != nil) {
            try container.encode(self.htmlVersion, forKey: .htmlVersion);
        }
        if (self.imageResolution != nil) {
            try container.encode(self.imageResolution, forKey: .imageResolution);
        }
        if (self.imagesFolder != nil) {
            try container.encode(self.imagesFolder, forKey: .imagesFolder);
        }
        if (self.imagesFolderAlias != nil) {
            try container.encode(self.imagesFolderAlias, forKey: .imagesFolderAlias);
        }
        if (self.metafileFormat != nil) {
            try container.encode(self.metafileFormat, forKey: .metafileFormat);
        }
        if (self.officeMathOutputMode != nil) {
            try container.encode(self.officeMathOutputMode, forKey: .officeMathOutputMode);
        }
        if (self.prettyFormat != nil) {
            try container.encode(self.prettyFormat, forKey: .prettyFormat);
        }
        if (self.resolveFontNames != nil) {
            try container.encode(self.resolveFontNames, forKey: .resolveFontNames);
        }
        if (self.resourceFolder != nil) {
            try container.encode(self.resourceFolder, forKey: .resourceFolder);
        }
        if (self.resourceFolderAlias != nil) {
            try container.encode(self.resourceFolderAlias, forKey: .resourceFolderAlias);
        }
        if (self.scaleImageToShapeSize != nil) {
            try container.encode(self.scaleImageToShapeSize, forKey: .scaleImageToShapeSize);
        }
        if (self.tableWidthOutputMode != nil) {
            try container.encode(self.tableWidthOutputMode, forKey: .tableWidthOutputMode);
        }
    }
        
    public func setAllowNegativeIndent(allowNegativeIndent : Bool?) {
        self.allowNegativeIndent = allowNegativeIndent;
    }
    
    public func getAllowNegativeIndent() -> Bool? {
        return self.allowNegativeIndent;
    }
    public func setCssClassNamePrefix(cssClassNamePrefix : String?) {
        self.cssClassNamePrefix = cssClassNamePrefix;
    }
    
    public func getCssClassNamePrefix() -> String? {
        return self.cssClassNamePrefix;
    }
    public func setCssStyleSheetFileName(cssStyleSheetFileName : String?) {
        self.cssStyleSheetFileName = cssStyleSheetFileName;
    }
    
    public func getCssStyleSheetFileName() -> String? {
        return self.cssStyleSheetFileName;
    }
    public func setCssStyleSheetType(cssStyleSheetType : String?) {
        self.cssStyleSheetType = cssStyleSheetType;
    }
    
    public func getCssStyleSheetType() -> String? {
        return self.cssStyleSheetType;
    }
    public func setDocumentSplitCriteria(documentSplitCriteria : String?) {
        self.documentSplitCriteria = documentSplitCriteria;
    }
    
    public func getDocumentSplitCriteria() -> String? {
        return self.documentSplitCriteria;
    }
    public func setDocumentSplitHeadingLevel(documentSplitHeadingLevel : Int?) {
        self.documentSplitHeadingLevel = documentSplitHeadingLevel;
    }
    
    public func getDocumentSplitHeadingLevel() -> Int? {
        return self.documentSplitHeadingLevel;
    }
    public func setEncoding(encoding : String?) {
        self.encoding = encoding;
    }
    
    public func getEncoding() -> String? {
        return self.encoding;
    }
    public func setExportDocumentProperties(exportDocumentProperties : Bool?) {
        self.exportDocumentProperties = exportDocumentProperties;
    }
    
    public func getExportDocumentProperties() -> Bool? {
        return self.exportDocumentProperties;
    }
    public func setExportDropDownFormFieldAsText(exportDropDownFormFieldAsText : Bool?) {
        self.exportDropDownFormFieldAsText = exportDropDownFormFieldAsText;
    }
    
    public func getExportDropDownFormFieldAsText() -> Bool? {
        return self.exportDropDownFormFieldAsText;
    }
    public func setExportFontResources(exportFontResources : Bool?) {
        self.exportFontResources = exportFontResources;
    }
    
    public func getExportFontResources() -> Bool? {
        return self.exportFontResources;
    }
    public func setExportFontsAsBase64(exportFontsAsBase64 : Bool?) {
        self.exportFontsAsBase64 = exportFontsAsBase64;
    }
    
    public func getExportFontsAsBase64() -> Bool? {
        return self.exportFontsAsBase64;
    }
    public func setExportHeadersFootersMode(exportHeadersFootersMode : String?) {
        self.exportHeadersFootersMode = exportHeadersFootersMode;
    }
    
    public func getExportHeadersFootersMode() -> String? {
        return self.exportHeadersFootersMode;
    }
    public func setExportImagesAsBase64(exportImagesAsBase64 : Bool?) {
        self.exportImagesAsBase64 = exportImagesAsBase64;
    }
    
    public func getExportImagesAsBase64() -> Bool? {
        return self.exportImagesAsBase64;
    }
    public func setExportLanguageInformation(exportLanguageInformation : Bool?) {
        self.exportLanguageInformation = exportLanguageInformation;
    }
    
    public func getExportLanguageInformation() -> Bool? {
        return self.exportLanguageInformation;
    }
    public func setExportListLabels(exportListLabels : String?) {
        self.exportListLabels = exportListLabels;
    }
    
    public func getExportListLabels() -> String? {
        return self.exportListLabels;
    }
    public func setExportOriginalUrlForLinkedImages(exportOriginalUrlForLinkedImages : Bool?) {
        self.exportOriginalUrlForLinkedImages = exportOriginalUrlForLinkedImages;
    }
    
    public func getExportOriginalUrlForLinkedImages() -> Bool? {
        return self.exportOriginalUrlForLinkedImages;
    }
    public func setExportPageMargins(exportPageMargins : Bool?) {
        self.exportPageMargins = exportPageMargins;
    }
    
    public func getExportPageMargins() -> Bool? {
        return self.exportPageMargins;
    }
    public func setExportPageSetup(exportPageSetup : Bool?) {
        self.exportPageSetup = exportPageSetup;
    }
    
    public func getExportPageSetup() -> Bool? {
        return self.exportPageSetup;
    }
    public func setExportRelativeFontSize(exportRelativeFontSize : Bool?) {
        self.exportRelativeFontSize = exportRelativeFontSize;
    }
    
    public func getExportRelativeFontSize() -> Bool? {
        return self.exportRelativeFontSize;
    }
    public func setExportRoundtripInformation(exportRoundtripInformation : Bool?) {
        self.exportRoundtripInformation = exportRoundtripInformation;
    }
    
    public func getExportRoundtripInformation() -> Bool? {
        return self.exportRoundtripInformation;
    }
    public func setExportTextBoxAsSvg(exportTextBoxAsSvg : Bool?) {
        self.exportTextBoxAsSvg = exportTextBoxAsSvg;
    }
    
    public func getExportTextBoxAsSvg() -> Bool? {
        return self.exportTextBoxAsSvg;
    }
    public func setExportTextInputFormFieldAsText(exportTextInputFormFieldAsText : Bool?) {
        self.exportTextInputFormFieldAsText = exportTextInputFormFieldAsText;
    }
    
    public func getExportTextInputFormFieldAsText() -> Bool? {
        return self.exportTextInputFormFieldAsText;
    }
    public func setExportTocPageNumbers(exportTocPageNumbers : Bool?) {
        self.exportTocPageNumbers = exportTocPageNumbers;
    }
    
    public func getExportTocPageNumbers() -> Bool? {
        return self.exportTocPageNumbers;
    }
    public func setExportXhtmlTransitional(exportXhtmlTransitional : Bool?) {
        self.exportXhtmlTransitional = exportXhtmlTransitional;
    }
    
    public func getExportXhtmlTransitional() -> Bool? {
        return self.exportXhtmlTransitional;
    }
    public func setFontResourcesSubsettingSizeThreshold(fontResourcesSubsettingSizeThreshold : Int?) {
        self.fontResourcesSubsettingSizeThreshold = fontResourcesSubsettingSizeThreshold;
    }
    
    public func getFontResourcesSubsettingSizeThreshold() -> Int? {
        return self.fontResourcesSubsettingSizeThreshold;
    }
    public func setFontsFolder(fontsFolder : String?) {
        self.fontsFolder = fontsFolder;
    }
    
    public func getFontsFolder() -> String? {
        return self.fontsFolder;
    }
    public func setFontsFolderAlias(fontsFolderAlias : String?) {
        self.fontsFolderAlias = fontsFolderAlias;
    }
    
    public func getFontsFolderAlias() -> String? {
        return self.fontsFolderAlias;
    }
    public func setHtmlVersion(htmlVersion : HtmlVersion?) {
        self.htmlVersion = htmlVersion;
    }
    
    public func getHtmlVersion() -> HtmlVersion? {
        return self.htmlVersion;
    }
    public func setImageResolution(imageResolution : Int?) {
        self.imageResolution = imageResolution;
    }
    
    public func getImageResolution() -> Int? {
        return self.imageResolution;
    }
    public func setImagesFolder(imagesFolder : String?) {
        self.imagesFolder = imagesFolder;
    }
    
    public func getImagesFolder() -> String? {
        return self.imagesFolder;
    }
    public func setImagesFolderAlias(imagesFolderAlias : String?) {
        self.imagesFolderAlias = imagesFolderAlias;
    }
    
    public func getImagesFolderAlias() -> String? {
        return self.imagesFolderAlias;
    }
    public func setMetafileFormat(metafileFormat : MetafileFormat?) {
        self.metafileFormat = metafileFormat;
    }
    
    public func getMetafileFormat() -> MetafileFormat? {
        return self.metafileFormat;
    }
    public func setOfficeMathOutputMode(officeMathOutputMode : OfficeMathOutputMode?) {
        self.officeMathOutputMode = officeMathOutputMode;
    }
    
    public func getOfficeMathOutputMode() -> OfficeMathOutputMode? {
        return self.officeMathOutputMode;
    }
    public func setPrettyFormat(prettyFormat : Bool?) {
        self.prettyFormat = prettyFormat;
    }
    
    public func getPrettyFormat() -> Bool? {
        return self.prettyFormat;
    }
    public func setResolveFontNames(resolveFontNames : Bool?) {
        self.resolveFontNames = resolveFontNames;
    }
    
    public func getResolveFontNames() -> Bool? {
        return self.resolveFontNames;
    }
    public func setResourceFolder(resourceFolder : String?) {
        self.resourceFolder = resourceFolder;
    }
    
    public func getResourceFolder() -> String? {
        return self.resourceFolder;
    }
    public func setResourceFolderAlias(resourceFolderAlias : String?) {
        self.resourceFolderAlias = resourceFolderAlias;
    }
    
    public func getResourceFolderAlias() -> String? {
        return self.resourceFolderAlias;
    }
    public func setScaleImageToShapeSize(scaleImageToShapeSize : Bool?) {
        self.scaleImageToShapeSize = scaleImageToShapeSize;
    }
    
    public func getScaleImageToShapeSize() -> Bool? {
        return self.scaleImageToShapeSize;
    }
    public func setTableWidthOutputMode(tableWidthOutputMode : String?) {
        self.tableWidthOutputMode = tableWidthOutputMode;
    }
    
    public func getTableWidthOutputMode() -> String? {
        return self.tableWidthOutputMode;
    }
}
