let config = Configuration(clientId: "####-####-####-####-####", clientSecret: "##################");
let api = WordsAPI(configuration: config);
let requestCommentRangeStartNode = NodeLink();
requestCommentRangeStartNode.setNodeId(nodeId: "0.3.0.3");
let requestCommentRangeStart = DocumentPosition();
requestCommentRangeStart.setNode(node: requestCommentRangeStartNode);
requestCommentRangeStart.setOffset(offset: 0);
let requestCommentRangeEndNode = NodeLink();
requestCommentRangeEndNode.setNodeId(nodeId: "0.3.0.3");
let requestCommentRangeEnd = DocumentPosition();
requestCommentRangeEnd.setNode(node: requestCommentRangeEndNode);
requestCommentRangeEnd.setOffset(offset: 0);
let requestComment = CommentInsert();
requestComment.setRangeStart(rangeStart: requestCommentRangeStart);
requestComment.setRangeEnd(rangeEnd: requestCommentRangeEnd);
requestComment.setInitial(initial: "IA");
requestComment.setAuthor(author: "Imran Anwar");
requestComment.setText(text: "A new Comment");
let insertRequest = InsertCommentRequest(name: "Sample.docx", comment: requestComment);
_ = try api.insertComment(request: insertRequest);