let config = Configuration(clientId: "####-####-####-####-####", clientSecret: "##################");
let api = WordsAPI(configuration: config);
let requestDataSaveOptions = SaveOptionsData();
requestDataSaveOptions.setFileName(fileName: "google.doc");
requestDataSaveOptions.setSaveFormat(saveFormat: "doc");
requestDataSaveOptions.setDmlEffectsRenderingMode(dmlEffectsRenderingMode: "1");
requestDataSaveOptions.setDmlRenderingMode(dmlRenderingMode: "1");
requestDataSaveOptions.setUpdateSdtContent(updateSdtContent: false);
requestDataSaveOptions.setZipOutput(zipOutput: false);
let requestData = LoadWebDocumentData();
requestData.setLoadingDocumentUrl(loadingDocumentUrl: "http://google.com");
requestData.setSaveOptions(saveOptions: requestDataSaveOptions);
let loadRequest = LoadWebDocumentRequest(data: requestData);
_ = try api.loadWebDocument(request: loadRequest);