let config = Configuration(clientId: "####-####-####-####-####", clientSecret: "##################");
let api = WordsAPI(configuration: config);
let requestFormField = FormFieldTextInput();
requestFormField.setName(name: "FullName");
requestFormField.setEnabled(enabled: true);
requestFormField.setCalculateOnExit(calculateOnExit: true);
requestFormField.setStatusText(statusText: "");
requestFormField.setTextInputType(textInputType: FormFieldTextInput.TextInputType.regular);
requestFormField.setTextInputDefault(textInputDefault: "No name");
let updateRequest = UpdateFormFieldRequest(name: "Sample.docx", index: 0, formField: requestFormField);
_ = try api.updateFormField(request: updateRequest);